### ISSUE TITLE
Find datasets

### ISSUE THREAD

**Issue by Rafael-Cardenas** [Rafael-Cardenas/Data-for-Good#3]
- [x] **Brainstorming** (explore different public datasets options)
> - Phoebe: We can check BC Housing or Census data from stat Canada
> - Rafael: I think we need historical data on housing prices, population growth (from census) and residential construction projects 
- [x] **Brightside** might have an opportunity to extend the analysis
- [x] Review purposed datasets
- [x] Choose the dataset or datasets that can help us with the objective of the project

**Comment by Rafael-Cardenas** [comment]
More details of purposed datasets on: https://docs.google.com/document/d/1PunROqWi9HXnVpImmy1AHWHLQ_VPvhzoe5uClV7lzTU/edit#

**Comment by Rafael-Cardenas** [comment]
After reading the Brightside Community Homes Annual Survey 2021 report I noticed:
- They study their community's characteristics (age, gender, sexual orientation, family members, and work status)
- Effects of covid 19 on their mental health and other aspects of their life (page 14)
- Satisfaction with the information received from Brightside’s newsletter (13% decrease)
- Study their health, happiness, and social connections
- There's a decrease in the participation for last year (their survey might be too long and the questions are the same as last year's)

**Conclusion**
I think the way Brightside could benefit from our study would be by comparing their rent prices to how Vancouver prices are increasing and the projections we could make

**Comment by Rafael-Cardenas** [comment]
- If we want to show how many houses were available for assistance programs in 2021 (BC Housing):
https://catalogue.data.gov.bc.ca/dataset/e6b53f5e-bbc9-4343-adf4-1d9e973422da/resource/4d07c941-59e4-4e0f-acc5-d71e2b97b147/download/mah-housing-continuum-march-31-2021-final.xlsx
-  For rent average and median prices for bachelor, 1 to 3 bedroom and historical data I purpose to use 
https://www03.cmhc-schl.gc.ca/hmip-pimh/en/Profile#TableMapChart/2410/3/Vancouver
- As a rule of thumb, a renter’s annual income should be 40 times their rent (30% of their total salary). Almost every rent-to-income ratio calculator you find online uses this alternative way to calculate the ratio

**Comment by Rafael-Cardenas** [comment]
Average and Median rent in 2021 & 2020





[Rent_Vancouver.xlsx](https://github.com/Rafael-Cardenas/Data-for-Good/files/9389367/Rent_Vancouver.xlsx)

**Comment by czhou-zhou** [comment]
[Census Data.xlsx](https://github.com/Rafael-Cardenas/Data-for-Good/files/9388587/Census.Data.xlsx)
Household median income
