### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by Rafael-Cardenas** [Rafael-Cardenas/Data-for-Good#4]
- [x] Clean data sets

**Comment by czhou-zhou** [comment]
Hi all,

Below is a projection on both population and housing done by metrovancouver.org. Feel free to take a look.
[Metro Vancouver Population dwelling units Projections .pdf](https://github.com/Rafael-Cardenas/Data-for-Good/files/9356920/Metro.Vancouver.Population.dwelling.units.Projections.pdf)
（http://www.metrovancouver.org/services/regional-planning/data-statistics/data-projections/Pages/default.aspx）
