### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by Rafael-Cardenas** [Rafael-Cardenas/Data-for-Good#5]

**Comment by ake700** [comment]
Here's the PDF copy of my RMarkdown and the datasets to go along with it. 
[Population_Forecast_RData.xlsx](https://github.com/Rafael-Cardenas/Data-for-Good/files/9438605/Population_Forecast_RData.xlsx)
[Population_AK.pdf](https://github.com/Rafael-Cardenas/Data-for-Good/files/9438606/Population_AK.pdf)

**Comment by Rafael-Cardenas** [comment]
**Dataset:** https://docs.google.com/spreadsheets/d/1M4wUNHa5wnQDJCxyONUM9hosm0y-3Te755upq9unz2E/edit?usp=sharing

This is what I modified for the data I used:
**Data Cleaning:**

- Area column was modified to be consistent in all the tables 
- Use only 2020 data
- Use only after-tax values

**Calculated values:**

- Household Median Income in the Rent table was calculated assuming that units have at least 1 person per room and that as a standard there are a maximum of 2 people per room
- Household Median Income for Bachelor and 1Bedroom units was calculated as an average income of 1 to 2 people
- Household Median Income for 2Bedroom units was calculated as an average income of 2 to 4 people
- Household Median Income for 3+Bedroom units was calculated as an average income of 3 to 4 people  

**Note: The United Nations considers densities of three or more persons per room to be overcrowded under any circumstance but states that this level may be raised or lowered for national use.

- Calculated average values for Langley DM & CY to match the area “Langley” in the Rent table
- Average values for census data were calculated to summarize the information from Coquitlam, Port Coquitlam & Port Moody, to match the area “Tri-cities” in the Rent table

References:
**Persons per room as an indicator of crowding ([Persons per room of private household (statcan.gc.ca)](https://www23.statcan.gc.ca/imdb/p3Var.pl?Function=DECI&Id=141438))
