### ISSUE TITLE
Outline microproject problem

### ISSUE THREAD

**Issue by Rafael-Cardenas** [Rafael-Cardenas/Data-for-Good#8]

**Comment by phoebechoi9292** [comment]
Rough problem statement that we can use as a starting point:

Immigration to British Columbia, has been one of the most important contributing factors to its growth over the past century. While Vancouver is the largest city in British Columbia and consistently ranked in the top three most livable cities in the entire world; it is likely to be desired destination for the newcomers.

We want people to stay, live, and build a future in our beautiful cities. To meet the needs of our growing population and ensure our cities remain vibrant and diverse, it’s important that we have an affordable and varied supply of housing. However, the lack of affordable housing has already put metro Vancouver in risk.

Throughout this project, we want to measure the current situation with big data and forecast the housing elasticity for the coming few years.

**Comment by phoebechoi9292** [comment]
The above problem statement is reviewed and finalized. Hence, I'm closing this issue and mark as done.
